Added missing add metadata source property translation [#1196]
comixed/comixed pull request #1198
Opened 2022-03-27 19:01 UTC by mcpierce

Closes #1196

## Status
READY

## Does this PR contain migrations?
NO

## Before You Submit Your PR:
- [ ] Have you announced your PR on the comixed-dev mailing list?
- [ ] New feature (non-breaking change which adds functionality)
- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] Refactors existing code (code changes for efficiency or maintainability)
- [ ] Security fix (be sure to include the CVE in the commit message) 
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [X] All new and existing tests passed.

2022-03-28 13:29 UTC, BRUCELLA2 requested changes

2022-03-28 13:29 UTC, BRUCELLA2 commented on comixed-webui/src/assets/i18n/fr/comic-metadata.json
> +      "use-metadata-source-id": "Scrape using the ComicVine id."
Why change these elements ?

2022-03-28 13:29 UTC, BRUCELLA2 commented on comixed-webui/src/assets/i18n/es/comic-metadata.json
> +      "skip-cache": "Scraping will {enabled, select, true{skip} other{use}} the scraping cache.",
Why change these elements ?
A remark in passing, I am not sure that the Spanish translation is relevant. "Issue" in English corresponds more to "número" than to "problema" which would be closer to "problem".

2022-03-28 15:03 UTC, mcpierce commented on comixed-webui/src/assets/i18n/es/comic-metadata.json
> +      "skip-cache": "Scraping will {enabled, select, true{skip} other{use}} the scraping cache.",
That was a mistake on my part: I forgot that I had copied some of the existing scraping translations into the metadata file. So when I added the missing translation entries I just copied the entire file over from english to spanish. That's why these were overwritten. I'll revert this set of changes.

2022-03-28 15:04 UTC, mcpierce commented on comixed-webui/src/assets/i18n/fr/comic-metadata.json
> +      "use-metadata-source-id": "Scrape using the ComicVine id."
See previous comment for the reason.

2022-04-01 09:00 UTC, BRUCELLA2 approved these changes

2022-04-01 12:16 UTC, merged