Added linking the collections chart to the collection page [#1256]
comixed/comixed pull request #1263
Opened 2022-05-02 12:14 UTC by mcpierce

Closes #1256 

## Status
READY

## Does this PR contain migrations?
NO

## Before You Submit Your PR:
- [ ] Have you announced your PR on the comixed-dev mailing list?
- [X] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Refactors existing code (code changes for efficiency or maintainability)
- [ ] Security fix (be sure to include the CVE in the commit message) 
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [X] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [X] I have added tests to cover my changes.
- [X] All new and existing tests passed.

2022-05-03 09:23 UTC, BRUCELLA2 requested changes
The case 'UNKNOWN' is not properly managed.
We have an empty page when we click on unknown publisher (or other collection type). We need to had this option in the filter in the CollectionDetailComponent.
Something like this : 
```
this.comics = entries.filter(comic => {
              switch (this.collectionType) {
                case CollectionType.PUBLISHERS:
                  if (this.collectionName === 'UNKNOWN') {
                    return comic.publisher === null;
                  } else {
                    return comic.publisher === this.collectionName;
                  }
```

2022-05-04 07:02 UTC, BRUCELLA2 commented
When you click on unknown nothing happens now. Is this what is desired? Wouldn't it be interesting to find out which elements of the collection are unknown to complete the information?

2022-05-04 10:46 UTC, mcpierce commented
It's a good suggestion. What would be a good way to communicate a null in such a case?

2022-05-06 06:49 UTC, BRUCELLA2 approved these changes

2022-05-06 06:49 UTC, merged