Added publishing the remote library state on comic update [#1327]
comixed/comixed pull request #1397
Opened 2022-08-17 00:32 UTC by mcpierce

**NOTE:** This PR is based on #1283 and that PR needs to be merged first.

Closes #1327 

## Status
READY

## Does this PR contain migrations?
NO

## Before You Submit Your PR:
- [ ] Have you announced your PR on the comixed-dev mailing list?
- [X] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Refactors existing code (code changes for efficiency or maintainability)
- [ ] Security fix (be sure to include the CVE in the commit message) 
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [X] I have added tests to cover my changes.
- [X] All new and existing tests passed.

2022-08-19 07:19 UTC, BRUCELLA2 commented
can you rebase this branch? It will remove the conflicts now and it will make the review easier :)

2022-08-19 18:34 UTC, mcpierce commented
> can you rebase this branch? It will remove the conflicts now and it will make the review easier :)

Rebased and pushed.

2022-08-20 10:24 UTC, BRUCELLA2 requested changes

2022-08-20 10:24 UTC, BRUCELLA2 commented on comixed-services/src/test/java/org/comixedproject/service/library/RemoteLibraryStateServiceTest.java
> +  @Mock private RemoteLibraryStateService remoteLibraryStateService;
To be deleted (not used)

2022-08-20 15:33 UTC, mcpierce commented on comixed-services/src/test/java/org/comixedproject/service/library/RemoteLibraryStateServiceTest.java
> +  @Mock private RemoteLibraryStateService remoteLibraryStateService;
Removed it.

2022-08-20 19:46 UTC, BRUCELLA2 approved these changes

2022-08-20 19:46 UTC, merged