Added REST API logging
comixed/comixed pull request #476
Opened 2020-08-19 22:16 UTC by mcpierce

## Status
**READY**

## Migrations
YES

## Description
Wraps annotated REST APIs and logs their runtime, request and response content, and any exceptions.

2020-08-21 20:32 UTC, BRUCELLA2 requested changes
I don't have a lot of knowledge in the field but it seems to me that the md5 is not very secure and it might be better to use BCryptPasswordEncoder provided by Spring Security to encode passwords.

There is few sonar issues to fix too.

2020-08-21 20:32 UTC, BRUCELLA2 commented on comixed-model/src/main/java/org/comixedproject/model/auditlog/RestAuditLogEntry.java
> +  private String emai;
I think "email" would be better ;)

2020-08-21 20:32 UTC, BRUCELLA2 commented on comixed-rest-api/src/main/java/org/comixedproject/authentication/ComiXedAuthenticationProvider.java
> +    ComiXedUser user = null;
you don't have to initialize user to null unless you want to be explicit, no?

2020-08-21 20:32 UTC, BRUCELLA2 commented on comixed-rest-api/src/main/java/org/comixedproject/authentication/ComiXedUserDetailsService.java
> +    ComiXedUser user = null;
Like before : you don't have to initialize user to null unless you want to be explicit, no?

2020-08-21 20:32 UTC, BRUCELLA2 commented on comixed-rest-api/src/main/java/org/comixedproject/authentication/ComiXedUserDetailsService.java
> +    result.roles(roles);
Couldn't something with forEach + lambda expression of new java versions be implemented?
Something like this (I don't know if it works, I haven't tested) :
    List<String> roles = new ArrayList<>();
    user.getRoles().forEach(role -> roles.add(role.getName()));
    result.roles(String.valueOf(roles));

2020-08-21 20:32 UTC, BRUCELLA2 commented on comixed-rest-api/src/main/java/org/comixedproject/controller/tasks/TaskController.java
> +      response.getResult().setEntries(entries);
set the result then get the result to set entries seems strange for me. 
Wouldn't it be more understandable to do it like this:
    try {
      final List<TaskAuditLogEntry> entries = this.taskService.getAuditLogEntriesAfter(cutoff);
      GetTaskAuditLogResponse taskAuditLogResponse = new GetTaskAuditLogResponse();
      taskAuditLogResponse.setEntries(entries);
      if (!entries.isEmpty()) {
        taskAuditLogResponse.setLatest(entries.get(entries.size() - 1).getStartTime());
      }
      response.setResult(taskAuditLogResponse);
      response.setSuccess(true);

2020-08-21 20:32 UTC, BRUCELLA2 commented on comixed-rest-api/src/main/java/org/comixedproject/authentication/AuthenticationConstants.java
>  public interface AuthenticationConstants {
According to sonar, it would be better to make a final class rather than an interface.

2020-08-21 20:55 UTC, mcpierce commented on comixed-model/src/main/java/org/comixedproject/model/auditlog/RestAuditLogEntry.java
> +  private String emai;
DOH! Fixed.

2020-08-21 20:56 UTC, mcpierce commented on comixed-rest-api/src/main/java/org/comixedproject/authentication/ComiXedAuthenticationProvider.java
> +    ComiXedUser user = null;
Java doesn't auto-initialize local variables to null, only instance variables.

2020-08-21 20:58 UTC, mcpierce commented on comixed-rest-api/src/main/java/org/comixedproject/authentication/ComiXedUserDetailsService.java
> +    ComiXedUser user = null;
See previous reply.

2020-08-21 21:01 UTC, mcpierce commented on comixed-rest-api/src/main/java/org/comixedproject/authentication/ComiXedUserDetailsService.java
> +    result.roles(roles);
The following call requires an array of String rather than a list. I could have done the above, but would have then it'd still have an extra call to create an array from the List. I think with the extra work it was just simpler to create the array directly.

2020-08-21 21:03 UTC, mcpierce commented on comixed-rest-api/src/main/java/org/comixedproject/authentication/AuthenticationConstants.java
>  public interface AuthenticationConstants {
Yeah, I had originally thought any entity who used it would implement the interface to have the values handy. I want to do a better job of this but not right now. ;)

2020-08-22 08:35 UTC, BRUCELLA2 commented
I have merged #479 before this PR. There are now some conflicts to be solved...

2020-08-22 11:19 UTC, mcpierce commented
> I don't have a lot of knowledge in the field but it seems to me that the md5 is not very secure and it might be better to use BCryptPasswordEncoder provided by Spring Security to encode passwords.
> 
> There is few sonar issues to fix too.

I agreed about MD5 vs BCrypt. Can you open that suggestion in a separate ticket? This story was solely meant to provide the REST audit logging.

2020-08-22 15:16 UTC, BRUCELLA2 approved these changes

2020-08-22 15:16 UTC, merged