Updated Spanish translation for 0.7 [#332]
comixed/comixed pull request #507
Opened 2020-09-16 08:14 UTC by theotocopulitos

## Status
READY

## Migrations
NO

## Description
Updated Spanish translation for 0.7 [#332]

2020-09-16 17:35 UTC, mcpierce requested changes
I saw a few entries that didn't get translated. Could you review the files and fix those entries, please?

For example, in library.json the clear-image-cache entries are still in english.

2020-09-16 17:35 UTC, mcpierce commented on comixed-frontend/src/assets/i18n/es/backend-status.json
>      "table": {
Can you translate these entries as well?

2020-09-16 19:26 UTC, theotocopulitos commented
Sorry :( ... not sure how I missed that...

But, regarding these lines:

    "page-title": "Detalles de la compilación",
    "table": {
      "branch": "Source Branch",
      "build-host": "Build Hostname",
      "build-time": "Built On",
      "build-version": "Version",
      "commit-user": "Committer Name",
      "commit-id": "Commit Hash",
      "commit-message": "Commit Message",
      "commit-time": "Time Of Last Commit",
      "dirty": "Built From Uncommitted Code?",
      "remote-origin-url": "Remote Origin",
      "jdbc-url": "JDBC Connection URL"
    }

I'd rather not translate them... this info relates to git, and there is not
a universal translation of those concepts. Anyone looking at these uses
them in English, I am guessing. Should you prefer me to translate that, I
will, but honestly, I think we should not.

On Wed, Sep 16, 2020 at 7:35 PM Darryl L. Pierce <notifications@github.com>
wrote:

> *@mcpierce* requested changes on this pull request.
>
> I saw a few entries that didn't get translated. Could you review the files
> and fix those entries, please?
>
> For example, in library.json the clear-image-cache entries are still in
> english.
> ------------------------------
>
> In comixed-frontend/src/assets/i18n/es/backend-status.json
> <https://github.com/comixed/comixed/pull/507#discussion_r489606336>:
>
> > @@ -30,7 +30,7 @@
>
>          "detail": "Error al recabar los datos de compilación..."
>
>        }
>
>      },
>
> -    "page-title": "Build Details",
>
> +    "page-title": "Detalles de la compilación",
>
>      "table": {
>
>
> Can you translate these entries as well?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/comixed/comixed/pull/507#pullrequestreview-489847088>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AALYAJ3TWOIEIAFTR2JRS5DSGDZOVANCNFSM4RON4QQQ>
> .
>

2020-09-16 19:56 UTC, mcpierce commented
Fair enough. Do other applications translate similar entries? I believe @BRUCELLA2 and @jmcrfp translated them, but you make a good point about them not being something to translate. Let's leave them untranslated here and we can discuss it in the dev list.

2020-09-17 08:37 UTC, theotocopulitos commented
I **think** I was able to squash all changes into a single commit!

2020-09-17 11:50 UTC, mcpierce approved these changes

2020-09-17 11:50 UTC, merged