Added clear REST API audit log [#483]
comixed/comixed pull request #533
Opened 2020-10-26 22:05 UTC by BRUCELLA2

## Status
**READY**

## Migrations
NO

## Description
* Added a button to clear the REST API audit log (only for Admin)

2020-10-26 22:30 UTC, BRUCELLA2 commented
I forgot the effects tests. I will add them.

2020-10-29 14:03 UTC, mcpierce commented on comixed-frontend/src/app/backend-status/effects/clear-rest-audit-log.effects.ts
> +            response.success ? restAuditLogCleared() : clearRestAuditLogFailed()
Would it be possible to have this return a mergeMap that includes the success action as well as an action to clear the loaded audit log?

2020-10-29 14:03 UTC, mcpierce requested changes
One question for the initial review.

2020-12-28 14:42 UTC, BRUCELLA2 commented
My pc is working properly again! So I made some modifications taking into account your remarks. I added the refresh of the rest log list after the clean. The code works but I'm not sure it's super clean because I'm not too familiar with actions, effects, reducers and selectors...

2020-12-28 22:02 UTC, mcpierce approved these changes
All looks good! Thanks for this!

2020-12-28 22:03 UTC, merged