Added a feature to load the server build details [#578]
comixed/comixed pull request #580
Opened 2021-01-02 17:08 UTC by mcpierce

## Status
**READY**

## Migrations
NO

## Description
 * Added the frontend feature to retrieve the details.
 * Refactored the REST APIs and repackaged the classes.
 * Added the page to display the build details.

2021-01-04 09:09 UTC, BRUCELLA2 requested changes
it's ok just a question and we can merge

2021-01-04 09:09 UTC, BRUCELLA2 commented on comixed-web/src/app/effects/build-details.effects.ts
> +  ) {}
Is it voluntary to place the builder at the end of the class?
In the other effects.ts files the constructor is placed at the beginning of the class. This is consistent with a field -> constructor -> method structure. If this is what you want, you will have to correct the other classes in the course of time.

2021-01-04 12:34 UTC, mcpierce commented on comixed-web/src/app/effects/build-details.effects.ts
> +  ) {}
I believe that's a side-effect of my IntelliJ setup and how it cleaned up the code. The constructor is the only pure method in the effect source module while the effect methods are generated by method calls to createEffect(). So IJ sorted those method calls above the constructor call. It's not a requirement for the code.

2021-01-05 08:05 UTC, BRUCELLA2 commented on comixed-web/src/app/effects/build-details.effects.ts
> +  ) {}
Okay, that's good then.

2021-01-05 08:07 UTC, BRUCELLA2 approved these changes

2021-01-05 08:07 UTC, merged