Fixed requiring Homebrew coreutils to use scripts on the Mac [#747]
comixed/comixed pull request #748
Opened 2021-05-30 12:58 UTC by mcpierce

## Status
READY

## Does this PR contain migrations?
NO

## Before You Submit Your PR:
- [X] Bug fix (non-breaking change which fixes an issue)
- [X] All new and existing tests passed.

2021-05-30 15:15 UTC, SinisterStairs approved these changes
This fixes the `realpath` issue for both Mojave (macOS 10.4) and Big Sur (macOS 11.4).  I didn't have a Catalina or pre-Mojave macOS system to test on, but I'd be genuinely surprised if it didn't also work.

2021-05-30 15:41 UTC, SinisterStairs commented
This patch fixed `run.sh` with Big Sur (macOS 11.4), but `java` itself core dumped.  (No issues with Mojave.)

I am using OpenJDK 16 on both those machines, as installed by Homebrew; but of note, my Big Sur* MBP also has Apple's M1** chip.  So the JRE core dump could be related to Homebrew not detecting the M1 chip and installing the M1 version of AdoptOpenJDK, or it could be that OpenJDK isn't compatible with the M1 chip.

I'm not going to spend much more time looking into this because I only cared about running ComiXed on my home computer or NAS; and on my work computer, Eclipse is running/debugging Java applications just fine (using its internal JDK).

*Mojave was the last macOS to support 32-bit applications (in addition to 64-bit), while Catalina and Big Sur are 64-bit only.  This caused problems for applications which weren't recompiled, but this isn't likely the problem here.

**In late 2020, Apple switched from Intel chips to their own M1 chip.  So in addition to running Big Sur, some MBP may be using the M1 chip rather than Intel.  This has added yet another compatibility vector.

2021-05-30 16:09 UTC, SinisterStairs requested changes
Actually this didn't completely fix the functionality of `realpath`:

The `run.sh` script works fine if I invoke it with `./run.sh` but when I tried `bin/run.sh` (from the source directory) I got:

Error: Unable to access jarfile ~/src/comixed-release-0.8.2-1.1/comixed-app-*.jar

So it dropped `bin/` from the path

EDIT:  Running it from my home directory with `./src/comixed-release-0.8.2-1.1/bin/run.sh` the realpath implementation returns my home directory, so it appears the realpath function is just returning the cwd

2021-05-30 16:16 UTC, SinisterStairs requested changes
I figured it out:  the realpath function is working, but the bash script needs to call it with just `realpath` instead of `realpath -s`

2021-05-30 18:15 UTC, mcpierce commented
> I figured it out: the realpath function is working, but the bash script needs to call it with just `realpath` instead of `realpath -s`
> 
> EDIT: We ought to do some regression testing to make sure the `realpath` function is compatible with Windows and *nix machines. Unfortunately both my Windows PC and NAS (*nix) are down atm, but as long as system supports bash, I don't see why it wouldn't.

I'll post an updated PR with the -s portion removed. I've got Linux boxes I can try them out on as well to be sure the script works there as well, though I agree with you that they should work just fine.

2021-06-03 13:19 UTC, mcpierce commented
@SinisterStairs Were you able to verify the updated PR as working? If so, please let me know and I'll merge it.

2021-06-03 14:53 UTC, SinisterStairs commented
It works for the happy path -- I'll comment in the source, but basically want to escape some variables.

I'm not sure I tested properly:  I downloaded the official release.zip, then cloned and checked out your branch, and replaced the release's run.sh with yours -- that worked in Mojave.

2021-06-03 14:56 UTC, mcpierce commented
@SinisterStairs Using the release archive but replacing the launch script should be a perfectly fine test; i.e., the script hasn't changed for the upcoming release.

I'll go ahead and merge this PR then and, if there are further issues, we can re-open the source ticket and take further action. And thank you for getting back to me.

2021-06-03 14:56 UTC, merged

2021-06-03 15:11 UTC, SinisterStairs reviewed
In addition to those lines, `COMIXED_JAR_FILE="${BINDIR}"/...` should be escaped

2021-06-03 15:11 UTC, SinisterStairs commented on comixed-release/src/main/assembly/scripts/run.sh
> +  [[ $1 = /* ]] && echo "$1" || echo "$PWD/${1#./}"
EDIT:  The first `$1` needs shell escaping so it works with filepaths containing spaces and other special characters:  `"$1"`

2021-06-03 15:11 UTC, SinisterStairs commented on comixed-release/src/main/assembly/scripts/run.sh
> +ME=$(realpath $0)
This needs to be shell escaped so it can handle directories with spaces in them (or other special characters):  `realpath "$0"`

2021-06-03 15:11 UTC, SinisterStairs commented on comixed-release/src/main/assembly/scripts/run.sh
>  BINDIR=$(dirname ${ME})
Also needs shell escaping, `dirname "${ME}"`

2021-06-03 15:11 UTC, SinisterStairs commented on comixed-release/src/main/assembly/scripts/run.sh
> +LIBDIR=$(realpath ${BINDIR}/../lib)
Shell escape `"${BINDIR}"`

2021-06-03 15:21 UTC, SinisterStairs commented
I should just make a merge request myself, but anyways, the happy path works